#!/bin/bash

# Fetch, configure, and build u-boot (http://git.denx.de/u-boot.git)
# x7fELF, x7fELF@gmail.com, 2016
# GNU GPLv3

# ./uboot_prepare arm arm-linux-gnueabihf- 2017.01 vexpress_ca9x4_defconfig -j 4

uboot_arch=${1:-arm}
uboot_cross_compile=${2:-arm-linux-gnueabihf-}
uboot_version=${3:-2017.01}
uboot_defconfig=${4:-vexpress_ca9x4_defconfig}
uboot_build_jobs=${5:--j 12}

uboot_fetch() {
	wget ftp://ftp.denx.de/pub/u-boot/u-boot-${uboot_version}.tar.bz2
	mkdir uboot
	tar -xvf u-boot-${uboot_version}.tar.bz2 --directory=uboot/ --strip-components=1
	pushd uboot
}

uboot_configure() {
	make ARCH=${uboot_arch} CROSS_COMPILE=${uboot_cross_compile} ${uboot_defconfig}
}

uboot_build() {
	make ARCH=${uboot_arch} CROSS_COMPILE=${uboot_cross_compile} ${uboot_build_jobs}
}

uboot_fetch
uboot_configure
uboot_build

